Bookstore/Models/Purchase.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore.Models
{
    public class Purchase
    {
        [Key]
        [BindNever]
        public int PurchaseId { get; set; }

        [BindNever]
        public ICollection<CartLineItem> Lines { get; set; }

        [Required(ErrorMessage = "Please enter a name.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter an address.")]
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }

        [Required(ErrorMessage = "Please enter a city name.")]
        public string City { get; set; }

        [Required(ErrorMessage = "Please enter a state.")]
        public string State { get; set; }
        public string Zip { get; set; }

        [Required(ErrorMessage = "Please enter a country.")]
        public string Country { get; set; }
        public bool Anonymous { get; set; }
        [BindNever]
        public bool PurchaseReceived { get; set; }
    }
}

Bookstore/Controllers/PurchaseController.cs
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private Cart cart { get; set; }
        public PurchaseController(IPurchaseRepository temp, Cart c)
        {
            repo = temp;
            cart = c;   
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }

        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            if (cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                purchase.Lines = cart.Items.ToArray();
                repo.SavePurchase(purchase);
                cart.ClearCart();

                return RedirectToPage("/PurchaseCompleted");  
            }

            else
            {
                return View();
            }
        }

    }
}

Bookstore/Views/Purchase/Checkout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Purchase

<h2>Check out now</h2>
<p>Please enter your details:</p>

<form method="post" asp-action="Checkout" asp-controller="Purchase">
    
    <div asp-validation-summary="All" class="text-danger"></div>
    
    <h4>Ship To:</h4>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
    </div>

    <h4>Address:</h4>
    <div class="form-group">
        <label asp-for="AddressLine1">Address Line 1: </label>
        <input asp-for="AddressLine1" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AddressLine2">Address Line 2: </label>
        <input asp-for="AddressLine2" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="AddressLine3">Address Line 3: </label>
        <input asp-for="AddressLine3" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="City">City: </label>
        <input asp-for="City" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="State">State: </label>
        <input asp-for="State" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Zip">Zip: </label>
        <input asp-for="Zip" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Country">Country: </label>
        <input asp-for="Country" class="form-control" />
    </div>

    <div class="checkbox">
        <label>
            <input asp-for="Anonymous" /> Purchase Anonymously
        </label>
    </div>

    <div class="float-end">
        <input class="btn btn-primary" type="submit" value="Complete Purchase" />
    </div>

</form>